import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://localhost:4317';
async function api(action,data={}){const r=await fetch(base+'/api/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return {status:r.status,body:await r.json()};}
const a=(await api('create',{name:'Alice test'})).body;
const b=(await api('join',{name:'Bob test',code:a.code})).body;
const controller=new AbortController();
const secondController=new AbortController();
let state;
const response=await fetch(`${base}/api/events?code=${a.code}&token=${a.token}`,{signal:controller.signal});
const secondResponse=await fetch(`${base}/api/events?code=${b.code}&token=${b.token}`,{signal:secondController.signal});
const secondConsume=(async()=>{try{for await(const chunk of secondResponse.body){}}catch(e){if(e.name!=='AbortError')throw e;}})();
const consume=(async()=>{let buffer='';try{for await(const chunk of response.body){buffer+=new TextDecoder().decode(chunk);let i;while((i=buffer.indexOf('\n\n'))>=0){const event=buffer.slice(0,i);buffer=buffer.slice(i+2);if(event.startsWith('data: '))state=JSON.parse(event.slice(6));}}}catch(e){if(e.name!=='AbortError')throw e;}})();
async function until(check){const start=Date.now();while(!check()){if(Date.now()-start>12000)throw Error('État attendu absent : '+state?.phase);await new Promise(r=>setTimeout(r,30));}}
try{
  await until(()=>state?.players.length===2);
  const snapshotResponse=await fetch(base+'/playlists/karaoke.json');
  assert.equal(snapshotResponse.status,200);
  const snapshot=await snapshotResponse.json();
  assert.equal(snapshot.exposedCount,100);
  assert.equal((await api('tracks',{...a,tracks:snapshot.tracks.filter(t=>t.url)})).status,200);
  await until(()=>state.tracks.length===100);
  assert(state.tracks.every(t=>!t.demo),'la playlist remplace la démo');
  assert.equal((await api('settings',{...b,mode:'title',rounds:1,seconds:10})).status,400,'seul l’hôte règle la partie');
  assert.equal((await api('start',a)).status,400,'les joueurs doivent être prêts');
  assert.equal((await api('settings',{...a,mode:'both',rounds:1,seconds:10})).status,200);
  await api('ready',{...a,ready:true});await api('ready',{...b,ready:true});await api('start',a);
  await until(()=>state?.phase==='loading');
  await api('audio-ready',{...a,roundId:state.round.id,ok:true});await api('audio-ready',{...b,roundId:state.round.id,ok:true});
  await until(()=>state?.phase==='countdown');
  assert(state.round.questions.every(q=>!('correct'in q)),'bonnes réponses cachées');
  assert.equal((await api('answer',{...a,selection:{}})).status,400,'réponse avant démarrage rejetée');
  await until(()=>state?.phase==='playing');
  const choice=Object.fromEntries(state.round.questions.map(q=>[q.field,q.options[0].id]));
  assert.equal((await api('joker',{...a,roundId:state.round.id,kind:'time'})).status,200);
  assert.equal((await api('answer',{...a,roundId:state.round.id,selection:choice})).status,200);
  assert.equal((await api('answer',{...a,roundId:state.round.id,selection:choice})).status,400,'pas de deuxième tentative');
  await api('answer',{...b,roundId:state.round.id,selection:choice});
  await until(()=>state?.phase==='reveal');
  assert.equal(state.round.results.length,2);assert(state.round.questions.every(q=>q.correct));
  assert(state.players.every(p=>p.score>=0&&p.score<=150));
  assert.equal((await api('reaction',{...a,reaction:'🔥'})).status,200);
  await until(()=>state?.phase==='finished');
  await api('restart',a);await until(()=>state?.phase==='lobby');
  assert(state.players.every(p=>p.score===0&&!p.ready));
  assert.equal((await api('transfer',{...a,playerId:state.players.find(p=>p.name==='Bob test').id})).status,200);
  assert.equal((await api('settings',{...b,settings:{input:'text',listening:'progressive',teams:true,bonus:true}})).status,200);
  assert.equal((await api('tracks',{...b,tracks:snapshot.tracks.slice(0,4)})).status,200);
  await api('ready',{...a,ready:true});await api('ready',{...b,ready:true});
  assert.equal((await api('start',b)).status,200);
  await until(()=>state?.phase==='loading');
  const roundId=state.round.id;
  await api('audio-ready',{...a,roundId,ok:true});await api('audio-ready',{...b,roundId,ok:true});
  await until(()=>state?.phase==='playing');
  assert(state.round.questions.every(q=>q.options.length===0),'mode écrit sans propositions');
  assert.deepEqual(state.round.stage.map(s=>s.length),[2,5,10]);
  const track=snapshot.tracks.find(t=>t.url===state.round.audio.url);assert(track);
  const aliceId=state.players.find(p=>p.name==='Alice test').id;
  const written={title:track.title,artist:track.artist};
  assert.equal((await api('answer',{...a,roundId,selection:written,bonus:aliceId})).status,200);
  assert.equal((await api('answer',{...b,roundId,selection:written,bonus:aliceId})).status,200);
  await until(()=>state?.phase==='finished');
  assert(state.players.every(p=>p.score===175));assert.equal(state.history.length,1);assert.equal(state.history[0].results.length,1);
  assert(state.teams.every(t=>t.score===175));
  await api('restart',b);await api('ready',{...a,ready:true});await api('ready',{...b,ready:true});await api('start',b);
  await until(()=>state?.phase==='loading');
  await api('audio-error',{...a,roundId:state.round.id});
  await until(()=>state?.phase==='reveal');assert(state.round.canceled);assert(state.players.every(p=>p.score===0));
  const c=(await api('create',{name:'Chloé test'})).body;
  assert(state.saved.length>=5,'sélections sauvegardées proposées');
  for(const s of state.saved)assert.equal((await api('playlist',{...c,saved:s.id})).status,200,`sélection ${s.id} importable`);
  assert.equal((await api('playlist',{...c,saved:'../package'})).status,400,'sélection inconnue refusée');
  console.log('OK : deux joueurs, QCM, réponse écrite progressive, équipes, bonus, joker, annulation audio, scores, récap, réaction, revanche, transfert de rôle et sélections sauvegardées.');
}finally{controller.abort();secondController.abort();await Promise.all([consume,secondConsume]);}
